CREATE DATABASE CatFeeding;

CREATE TABLE Users (
	     Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	  Login VARCHAR(100),
   Password VARCHAR(100),
   Nickname NVARCHAR(100),
       Role NVARCHAR(50)
);

CREATE TABLE Pets (
	     Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	   Name VARCHAR(50),
       Owner_Id INT NOT NULL FOREIGN KEY REFERENCES Users
);

CREATE TABLE FeedTime (
	     Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	    User_Id INT NOT NULL FOREIGN KEY REFERENCES Users,
		 Pet_Id INT NOT NULL FOREIGN KEY REFERENCES Pets,
	  Feed_Time DATETIME2(7)
);

CREATE TABLE UsersPets (
	     Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	    User_Id INT NOT NULL FOREIGN KEY REFERENCES Users,
		 Pet_Id INT NOT NULL FOREIGN KEY REFERENCES Pets,
);